apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ (include "kube_info.fullname" .) }}-clusterrolebinding
  labels:
    {{- include "kube_info.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: kube-info
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ (include "kube_info.fullname" .) }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ (include "kube_info.namespace" .) }}