apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ (include "kube_info.fullname" .) }}-daemonset
  namespace: {{ (include "kube_info.namespace" .) }}
  labels:
    {{- include "kube_info.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: kube-info
spec:
  selector:
    matchLabels:
      app: kube-info
  template:
    metadata:
      labels:
        app: kube-info
        {{- include "kube_info.metaLabels" . | nindent 8 }}
        app.kubernetes.io/component: kube-info
    spec:
      serviceAccountName: {{ .Values.serviceaccount.name }}
      containers:
      - name: kube-info
        image: "{{ (include "kube_info.image" .) }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
