apiVersion: v1
kind: Service
metadata:
  name: kubeinfo-service
  namespace: {{ (include "kube_info.namespace" .) }}
  labels:
    {{- include "kube_info.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: kube-info
spec:
  selector:
    app: kube-info
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
