{{- if .Values.serviceaccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ (include "kube_info.namespace" .) }}
  labels:
    {{- include "kube_info.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: kube-info
{{- end }}