name: Release Helm Chart

on:
  push:
    branches: [helm_release]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: helm
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_repo_url: https://github.com/Mileshin/kube-info
    # - name: Setup Helm
    #   uses: azure/setup-helm@v4.2.0

    # - name: Package Helm Chart
    #   run: |
    #     helm package ./helm
    #     mv *.tgz kube-info.tgz

    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: ${{ github.ref_name }}
    #     name: Release ${{ github.ref_name }}
    #     body: |
    #       New Helm Chart release for version ${{ github.ref_name }}.
    #       - Packaged chart: `kube-info.tgz`
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create GitHub Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: packaged-chart.tgz
    #     tag: ${{ github.ref_name }}
    #     release_name: Helm Chart ${{ github.ref_name }}
    #     body: |
    #       New Helm Chart release for version ${{ github.ref_name }}.
    #       - Packaged chart: `packaged-chart.tgz`